name: Mirror to Codeberg

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  codeberg_mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Required to mirror all history/branches

      - name: Mirror Repository to Codeberg
        uses: cssnr/mirror-repository-action@v1
        with:
          # Use 'url' instead of 'remote_url'
          url: "https://codeberg.org/sreehari425/q6w.git"
          username: sreehari425
          password: ${{ secrets.CODEBERG_TOKEN }}
          create: true # Automatically creates the repo on Codeberg if missing
